.TH SPACEFM: "1" "November 2012" "spacefm:0.8.2" "User Commands"
.SH NAME
spacefm: \- manual page for spacefm: Unknown option --version
.SH DESCRIPTION
.SS "Usage:"
.IP
spacefm [OPTION...] [DIR | FILE | URL]...
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-t\fR, \fB\-\-new\-tab\fR
Open folders in new tab of last window (default)
.TP
\fB\-r\fR, \fB\-\-reuse\-tab\fR
Open folder in current tab of last used window
.TP
\fB\-n\fR, \fB\-\-no\-saved\-tabs\fR
Don't load saved tabs
.TP
\fB\-w\fR, \fB\-\-new\-window\fR
Open folders in new window
.TP
\fB\-p\fR, \fB\-\-panel\fR=\fIP\fR
Open folders in panel 'P' (1\-4)
.TP
\fB\-\-desktop\fR
Launch desktop manager daemon
.TP
\fB\-\-desktop\-pref\fR
Show desktop settings
.TP
\fB\-\-show\-pref\fR=\fIN\fR
Show Preferences ('N' is the Pref tab number)
.TP
\fB\-d\fR, \fB\-\-daemon\-mode\fR
Run as a daemon
.TP
\fB\-c\fR, \fB\-\-config\-dir\fR=\fIDIR\fR
Use DIR as configuration directory
.TP
\fB\-f\fR, \fB\-\-find\-files\fR
Show File Search
.TP
\fB\-\-set\-wallpaper\fR
Set desktop wallpaper to FILE
.TP
\fB\-g\fR, \fB\-\-dialog\fR
Show a custom dialog (See \fB\-g\fR help)
.TP
\fB\-\-profile\fR=\fIPROFILE\fR
No function \- for compatibility only
.TP
\fB\-\-no\-desktop\fR
No function \- for compatibility only
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH "SEE ALSO"
The full documentation for
.B spacefm:
at <http://ignorantguru.github.com/spacefm/>
.PP
.SH AUTHOR
"Super" Nathan Weber <supernathansunshine@gmail.com>
